version: '3.11'

services:
  proxy_api:
    image: node:18-alpine
    restart: unless-stopped
    environment:
      PORT: 8082

    working_dir: /app
    command: sh -c "yarn install --immutable && yarn start"

    ports:
      - 8082:8082

    volumes:
      - ./:/app
